### ISSUE TITLE
2. Create the Campaign DataFrame

### ISSUE THREAD

**Issue by JulieKent** [JulieKent/BootCamp_Crowdfunding_ETL#2]

**Comment by LarisaXiang** [comment]
To complete this part, I had to create category and subcategory DataFrames first. I have these two CSV files saved in my local repo without uploading them. This may cause the code to not run successfully. Happy to change the path later when part 1 is done by Amey :)

**Comment by JulieKent** [comment]
Thanks Larissa,
This is a good thing to note in the reflection being that different data tables may have dependencies.  While we made a plan to split the load, we didn't plan the order that the tasks needed to be done in to support data dependencies.  You can upload the csv files you created to support the running of your code.  When Amey produces his portion, it will overwrite those csv files anyway.

**Comment by JulieKent** [comment]
Section has been amended and added to main notebook. Original notebook added to a new folder called Original_NBs.
